### ISSUE TITLE
github action workflow to auto-update workflow files on a cron?

### ISSUE THREAD

**Issue by ljharb** [fregante/ghat#28]
Is there any chance you have an existing action that will run ghat, and if needed, commit and push the changes, so I can set it up with a cron?

**Comment by fregante** [comment]
I don't have it and I'd rather not make one since the readme says it's not meant to be used that way (since there's no versioning, it could very well be a footgun)

I think it would be as easy as:

```yml
- uses: fregante/setup-git-user@v1
- run: npx ghat
- run: git commit -m 'Workflow updates' -a || true
- run: git push origin HEAD:master
```
